name: Build and Publish Unison
on:
  workflow_run:
    workflows: ["Tag on VERSION bump"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to access tags

      - name: Get latest tag
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0 --match="v*" | sed 's/^v//')
          if [[ -z "$VERSION" ]]; then
            echo "No valid tag found matching v*"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/senseware/unison:v${{ steps.get_version.outputs.version }}
            ghcr.io/senseware/unison:latest
