name: Tag on VERSION bump

on:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out full history so we can push tags
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Read the version and create an annotated tag
      - name: Create Git tag
        run: |
          VERSION=$(cat VERSION)
          echo "Tagging release v$VERSION"
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"
